ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

export EDITOR=vim
export PATH=$PATH:$HOME/bin

export RUBY_GC_HEAP_INIT_SLOTS=1000000
export RUBY_HEAP_SLOTS_INCREMENT=1000000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_MALLOC_LIMIT=100000000
export RUBY_HEAP_FREE_MIN=500000

export CC=/usr/local/bin/gcc-4.2
export CPPFLAGS=-I/opt/X11/include

plugins=(git bundler osx ruby rails brew cap gem rake ssh-agent)

source $ZSH/oh-my-zsh.sh
unsetopt correct_all

if [ -e "$HOME/dotfiles/zsh/functions.sh" ]; then
  source "$HOME/dotfiles/zsh/functions.sh"
fi

if [ -e "$HOME/dotfiles/zsh/aliases.sh" ]; then
  source "$HOME/dotfiles/zsh/aliases.sh"
fi

# Customize to your needs...
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:$PATH"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH="$PATH:$HOME/bin"
