ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

export EDITOR=vim
export PATH=$PATH:$HOME/bin
export PATH=/usr/local/share/npm/bin:$PATH

export RUBY_HEAP_MIN_SLOTS=1000000
export RUBY_HEAP_SLOTS_INCREMENT=1000000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_MALLOC_LIMIT=100000000
export RUBY_HEAP_FREE_MIN=500000

export CC=/usr/local/bin/gcc-4.2
export CPPFLAGS=-I/opt/X11/include

export MY_SANDBOX=sandbox2

plugins=(git bundler osx ruby rails brew cap gem rake ssh-agent)

source $ZSH/oh-my-zsh.sh
unsetopt correct_all

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
[[ -s "$HOME/.nvm/nvm.sh" ]] && . "$HOME/.nvm/nvm.sh"


if [ -e "$HOME/dotfiles/zsh/functions.sh" ]; then
  source "$HOME/dotfiles/zsh/functions.sh"
fi

if [ -e "$HOME/dotfiles/zsh/aliases.sh" ]; then
  source "$HOME/dotfiles/zsh/aliases.sh"
fi

if [ -e "$HOME/dotfiles/zsh/otb.sh" ]; then
  source "$HOME/dotfiles/zsh/otb.sh"
fi

# Customize to your needs...
export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/X11/bin:/Users/barbared/.rvm/bin:/usr/local/sbin:/usr/local/mysql/bin:/Users/barbared/Code/247/unicorns:/usr/local/lib/node:/usr/local/share/npm/bin:$PATH"

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
